name:                instana-haskell-trace-sdk
version:             0.5.0.1
github:              "instana/haskell-trace-sdk"
license:             BSD3
author:              "Bastian Krol"
maintainer:          "bastian.krol@instana.com"
copyright:           "Bastian Krol 2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please also see the README on Github at <https://github.com/instana/haskell-trace-sdk#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

