resolver: lts-16.7

packages:
- .

extra-deps:
- aeson-extra-0.4.1.3@sha256:8ad8e4d28e46280ea98af2e94dcaaf524c396c9d91b1eba867961efc6e7f923f,2997


# Example App Docker Image
# To build it on any non-Linux OS, run
#   stack docker pull
# once, then build with
#   stack image container --docker
# On Linux you can omit `stack docker pull` and build without --docker, like
# this:
#   stack image container
image:
  container:
    base: basti1302/fpco-stack-run-extended
    name: basti1302/instana-haskell-trace-sdk-example-exe
    executables:
    - instana-haskell-example-exe
