resolver: lts-11.5

packages:
- .

# Example App Docker Image
# To build it on any non-Linux OS, run
#   stack docker pull
# once, then build with
#   stack image container --docker
# On Linux you can omit `stack docker pull` and build without --docker, like
# this:
#   stack image container
image:
  container:
    base: basti1302/fpco-stack-run-extended
    name: basti1302/instana-haskell-trace-sdk-example-exe
    executables:
    - instana-haskell-example-exe

