# See https://circleci.com/docs/2.0/language-haskell/.

version: 2.1

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
        auth:
          username: instanahaskelltracesdk
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - v1-haskell-sdk-{{ .Environment.CIRCLE_JOB }}-{{ checksum "instana-haskell-trace-sdk.cabal" }}-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - v1-haskell-sdk-{{ .Environment.CIRCLE_JOB }}

      - run:
          name: Resolve/Update Dependencies
          command: "stack --no-terminal setup"

      - run:
          name: Build and run tests
          command: "date && TEST_LOG_LEVEL=DEBUG stack --no-terminal test"

      - run:
          name: Verify that source distribution tarballs can be built
          command: "date && stack sdist"

      - run:
          name: Verify that documentation can be built
          command: "date && stack haddock --no-haddock-deps"

      - save_cache:
          name: Cache Dependencies
          key: v1-haskell-sdk-{{ .Environment.CIRCLE_JOB }}-{{ checksum "instana-haskell-trace-sdk.cabal" }}-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.ghc"
            - "/root/.cabal"
            - "/root/.stack"
            - ".stack-work"
