# This github action publishes a release on-demand. It can be triggered
# manually. Before actually publishing a release, it will check whether there
# are successful CircleCI builds for the commit that is to be released.
name: release-on-demand

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry Run"
        required: false
        default: false
        type: choice
        options:
        - false
        - true
      skipCiStatusCheck:
        description: "Skip CI status check"
        required: false
        default: false
        type: choice
        options:
        - false
        - true

jobs:
  publish-release:
    name: Release the main branch as a new version on hackage.
    runs-on: ubuntu-latest
    env:
      CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
      DRY_RUN: ${{ inputs.dryRun }}
      SKIP_CI_STATUS_CHECK: ${{ inputs.skipCiStatusCheck }}
    steps:
      - uses: actions/checkout@v3
        with:
          # With fetch-depth 0 the checkout action will also fetch all tags and
          # branches. We need the tags to determine the changes since the
          # last relase.
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'npm'
          cache-dependency-path: 'bin/release-util/package-lock.json'

      - name: echo versions
        run: |
          node --version
          npm --version

      - name: check CircleCI status
        run: |
          if [[ $SKIP_CI_STATUS_CHECK != true ]]; then
            bin/release-util/check-circle-ci-status.js
          fi

      - name: install dependencies of release-util
      - run: |
          cd bin/release-util && npm ci

      - name: configure git name/email
        run: |
          git config user.name "IBM/Instana/Team Haskell"
          git config user.email github-actions@github.com

      - name: publish release
        run: bin/release.sh
